- name: Check and Download Windows Updates
  hosts: all
  tasks:
    - name: Check for updates
      ansible.windows.win_updates:
        state: searched
        log_path: c:\updates.txt
      register: updatelist
    - name: Download updates
      ansible.windows.win_updates:
        state: downloaded
        log_path: c:\downloaded.txt
    - debug: var=updatelist