- name: Check Linux Updates
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - name: Check Distribution
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
  - name: Ubuntu - Update Apt Cache
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  - name: Ubuntu - List Available Updates
    ansible.builtin.command: apt list --upgradable
    register: apt_updates
  - debug: msg="{{ apt_updates }}"