- name: Check Linux Updates
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - name: Ubuntu - Update Apt Cache
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  - name: Ubuntu - List Available Updates
    ansible.builtin.command: apt list --upgradable
    register: apt_updates
    when: ansible_distribution == "Ubuntu"
  - debug: msg="{{ apt_updates.stdout_lines }}"
    when: ansible_distribution == "Ubuntu"
  - name: CentOS - Update Yum Cache
    ansible.builtin.yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"
  - name: CentOS - List Available Updates
    ansible.builtin.command: yum check-update
    register: yum_updates
    when: ansible_distribution == "CentOS"
    failed_when:
      - yum_updates.rc == 1
  - debug: msg="{{ yum_updates.stdout_lines }}"
    when: ansible_distribution == "CentOS"