- name: Check Linux Updates
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - name: Check Distribution
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
  - name: Check Ubuntu Updates
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_distribution == "Ubuntu"