- name: Check Linux Updates
  hosts: all
  gather_facts: yes
  tasks:
  - name: Check Distribution
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"