- name: Install Windows Updates No Reboots
  hosts: all
  tasks:
    - name: Install Updates
      ansible.windows.win_updates:
        category_names: '*'
        reboot: no
        log_path: C:\windows\temp\installupdates.txt